title: SE Conference Deadlines # (Maintained by @gluckzhang)
email: longz@kth.se
description: Countdowns to top software engineering conference deadlines
author: Abhishek Das

# domain: ""
baseurl: ""

github_username: gluckzhang
github_repo: se-deadlines

markdown: kramdown
